import { NextResponse } from "next/server";
export async function GET() {
  return NextResponse.json({
    ok: true,
    service: "career-copilot-v2",
    version: "1.1.0",
    runtime: "cloudflare-workers",
    mode: process.env.APP_MODE ?? "demo",
    controlPlane: "approval-first",
    authRequired: true,
    automaticSubmission: false,
    automaticInterviewAcceptance: false,
    automaticOfferAcceptance: false,
    publicSourceDiscovery: true,
    gmailDraftOnly: true,
    interviewLearningLoop: true,
    conversionAnalytics: true,
    weeklyReviews: true,
    operationalObservability: true,
    documentKnowledgeBase: true,
    pgvectorRetrieval: true,
    citationRequired: true,
    durableHumanInterrupts: true,
    automaticEvidencePromotion: false,
    agentRuntime: true,
    hybridJobRanking: true,
    resumePersonas: ["agent_engineer", "ai_product", "ai_solution", "local_transition"],
    mcpServer: true,
    mcpProtocolVersion: "2025-06-18",
    agentEvaluation: true,
    publicPortfolioPlayground: true,
    deterministicAgentDemoApi: true,
    dockerDemoStack: true,
    automaticEmailSend: false,
    completeUserProfiles: true,
    privateMultiResumeLibrary: true,
    perUserDailyRecommendations: true,
    automaticApplicationPreparation: true,
    completeApplicationKits: true,
    tailoredResumePrintExport: true,
    emailComposeHandoff: true,
    oneClickApplicationHandoff: true,
    automaticExternalSubmission: false,
    materialExports: ["markdown", "json", "html", "eml", "kit", "resume", "answers"],
    supabaseConfigured: Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY),
    timestamp: new Date().toISOString(),
  });
}
