import { NextResponse } from "next/server";
import { RELEASE } from "@/lib/release";
import { RESUME_PERSONAS } from "@/lib/agent-runtime.mjs";
export async function GET() {
  return NextResponse.json({
    ok: true,
    service: "career-copilot-v2",
    version: RELEASE.version,
    releaseLine: RELEASE.releaseLine,
    mcpProtocolVersion: RELEASE.mcpProtocolVersion,
    runtime: "cloudflare-workers",
    mode: process.env.APP_MODE ?? "demo",
    controlPlane: "approval-first",
    authRequired: true,
    automaticSubmission: RELEASE.safety.automaticSubmission,
    automaticInterviewAcceptance: RELEASE.safety.automaticInterviewAcceptance,
    automaticOfferAcceptance: RELEASE.safety.automaticOfferAcceptance,
    publicSourceDiscovery: true,
    sourceUrlAutoDetection: true,
    sourceConnectionTesting: true,
    recruitmentPlatformSearch: true,
    clickableSourceCards: true,
    instantProfileAggregateSearch: true,
    indexedRecruitmentPlatformSearch: true,
    perPlatformSearchFeedback: true,
    automaticSearchResultPreparation: true,
    gmailDraftOnly: true,
    interviewLearningLoop: true,
    conversionAnalytics: true,
    weeklyReviews: true,
    operationalObservability: true,
    documentKnowledgeBase: true,
    pgvectorRetrieval: true,
    citationRequired: true,
    durableHumanInterrupts: true,
    automaticEvidencePromotion: false,
    agentRuntime: true,
    hybridJobRanking: true,
    resumePersonas: Object.keys(RESUME_PERSONAS),
    mcpServer: true,
    agentEvaluation: true,
    publicPortfolioPlayground: true,
    deterministicAgentDemoApi: true,
    dockerDemoStack: true,
    automaticEmailSend: RELEASE.safety.automaticEmailSend,
    completeUserProfiles: true,
    privateMultiResumeLibrary: true,
    perUserDailyRecommendations: true,
    automaticApplicationPreparation: true,
    completeApplicationKits: true,
    guidedOnboarding: true,
    recommendationFeedback: true,
    groupedDailyRecommendations: true,
    sourceHealthGuidance: true,
    editableApplicationMaterials: true,
    applicationMaterialVersions: true,
    tailoredResumeDocxExport: true,
    applicationFollowUpTracking: true,
    scalableSourceCatalog: true,
    advancedJobDeduplication: true,
    jobLifecycleDetection: true,
    recommendationBehaviorLearning: true,
    inAppNotifications: true,
    fullProductFunnelAnalytics: true,
    tailoredResumePrintExport: true,
    emailComposeHandoff: true,
    oneClickApplicationHandoff: true,
    automaticExternalSubmission: RELEASE.safety.automaticSubmission,
    materialExports: ["markdown", "json", "html", "eml", "kit", "resume", "answers"],
    supabaseConfigured: Boolean((process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL) && (process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY)),
    timestamp: new Date().toISOString(),
  });
}
