export const RESUME_PERSONAS: Record<string, { label: string; roleFamily: string; prioritySkills: string[]; projectOrder: string[]; emphasis: string[]; summary: string }>;
export const MCP_TOOL_DEFINITIONS: Array<Record<string, any>>;
export function extractJobSkills(job: Record<string, any>): string[];
export function buildJobCitation(job: Record<string, any>): Record<string, any>;
export function buildEvidenceCitation(item: Record<string, any>): Record<string, any>;
export function calculateRuleScore(job: Record<string, any>, evidence?: Array<Record<string, any>>): Record<string, any>;
export function calculateSemanticScore(job: Record<string, any>, evidence?: Array<Record<string, any>>): Record<string, any>;
export function calculateHistoryScore(job: Record<string, any>, applications?: Array<Record<string, any>>): Record<string, any>;
export function rankJobHybrid(job: Record<string, any>, evidence?: Array<Record<string, any>>, applications?: Array<Record<string, any>>): Record<string, any>;
export function rankJobsHybrid(jobs?: Array<Record<string, any>>, evidence?: Array<Record<string, any>>, applications?: Array<Record<string, any>>): Array<{ job: Record<string, any>; score: Record<string, any> }>;
export function recommendResumePersona(job: Record<string, any>, score?: Record<string, any> | null): string;
export function buildGreetingDraft(input: { job: Record<string, any>; score?: Record<string, any> | null; persona?: string | null }): Record<string, any>;
export function generateResumeDraft(input: { persona?: string; job: Record<string, any>; evidence?: Array<Record<string, any>>; score?: Record<string, any> | null }): Record<string, any>;
export function evaluateGrounding(input: { output?: string; citations?: Array<Record<string, any>>; expectedEvidenceIds?: string[] }): Record<string, any>;
export function evaluateRetrieval(input: { relevantIds?: string[]; resultIds?: string[]; k?: number }): Record<string, any>;
export function buildDailyAgentReport(ranked?: Array<any>, skillGaps?: Array<Record<string, any>>, reportDate?: string): Record<string, any>;
export function routeAgentTask(taskType: string): string[];
export function createTrace(nodeName: string, sequenceNo: number, inputSummary?: Record<string, any>, outputSummary?: Record<string, any>, evidenceRefs?: Array<Record<string, any>>): Record<string, any>;
