export function sha256Hex(value: unknown): string;
export function normalizeDocumentText(value: unknown): string;
export function chunkDocument(input: unknown, options?: Record<string, unknown>): Array<Record<string, any>>;
export function tokenize(value: unknown): string[];
export function lexicalScore(query: unknown, content: unknown, heading?: unknown): number;
export function rankLexicalChunks(query: unknown, chunks: Array<Record<string, any>>, limit?: number): Array<Record<string, any>>;
export function citationForChunk(chunk: Record<string, any>): Record<string, any>;
export function buildEvidenceCandidate(chunk: Record<string, any>, input?: Record<string, any>): Record<string, any>;
export function normalizeWorkflowDecision(input: Record<string, any>): Record<string, any>;
export function applyEvidenceDecision(candidate: Record<string, any>, input: Record<string, any>): Record<string, any>;
export function buildRagContext(query: unknown, results: Array<Record<string, any>>): Record<string, any>;
