-- Career Copilot V2 Milestone 02
-- Engineering evidence: model runtime observability and AI Coding delivery records.

create table if not exists public.model_runs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  provider text not null,
  model_name text not null,
  endpoint text not null,
  prompt_hash text not null,
  input_chars integer not null default 0 check (input_chars >= 0),
  output_chars integer not null default 0 check (output_chars >= 0),
  latency_ms integer not null default 0 check (latency_ms >= 0),
  success boolean not null default false,
  error text,
  created_at timestamptz not null default now()
);

create index if not exists model_runs_user_created_idx
  on public.model_runs(user_id, created_at desc);
create index if not exists model_runs_success_created_idx
  on public.model_runs(success, created_at desc);

create table if not exists public.delivery_runs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  project text not null,
  task_name text not null,
  agent_tool text not null,
  started_at timestamptz not null,
  finished_at timestamptz not null,
  duration_minutes numeric(10,2) not null check (duration_minutes >= 0),
  files_changed integer not null default 0 check (files_changed >= 0),
  ai_generated_lines integer not null default 0 check (ai_generated_lines >= 0),
  human_edited_lines integer not null default 0 check (human_edited_lines >= 0),
  tests_run integer not null default 0 check (tests_run >= 0),
  tests_passed integer not null default 0 check (tests_passed between 0 and tests_run),
  acceptance_criteria_total integer not null default 0 check (acceptance_criteria_total >= 0),
  acceptance_criteria_met integer not null default 0 check (acceptance_criteria_met between 0 and acceptance_criteria_total),
  notes text,
  source_ref text,
  created_at timestamptz not null default now(),
  constraint delivery_runs_time_order check (finished_at >= started_at)
);

create index if not exists delivery_runs_user_finished_idx
  on public.delivery_runs(user_id, finished_at desc);
create index if not exists delivery_runs_user_project_idx
  on public.delivery_runs(user_id, project, finished_at desc);

alter table public.model_runs enable row level security;
alter table public.delivery_runs enable row level security;

create policy "users read own model runs"
  on public.model_runs for select
  using (auth.uid() = user_id);
create policy "users insert own model runs"
  on public.model_runs for insert
  with check (auth.uid() = user_id);

create policy "users read own delivery runs"
  on public.delivery_runs for select
  using (auth.uid() = user_id);
create policy "users insert own delivery runs"
  on public.delivery_runs for insert
  with check (auth.uid() = user_id);
create policy "users update own delivery runs"
  on public.delivery_runs for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
